--- 
production: 
  plugins: greyresults, inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  title: US Self Storage Locator
  theme: storagelocator
  widgets: 
  description: ""
  keywords: ""
development: !map:HashWithIndifferentAccess 
  plugins: greyresults, inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  title: US Self Storage Locator
  theme: storagelocator
  description: some description
  keywords: some keywords
test: 
  plugins: greyresults, inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  theme: storagelocator
  title: US Self Storage Locator
  widgets: 
  description: 
  keywords: 
