development:
  adapter: mysql
  encoding: utf8
  database: usselfstoragelocator
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  database: usselfstoragelocator
  username: root
  password: 

