development:
    encoding: unicode
    adapter: postgresql
    username: postgres
    port: 5432
    host: localhost
    database: usselfstoragelocator
    password: 09i-0op

production:
    encoding: unicode
    adapter: postgresql
    username: postgres
    port: 5432
    host: localhost
    database: usselfstoragelocator
    password: 09i-0op