license_key: 57aabee0ced0afefbf60c9aae0cd912189fca6dc
app_name: storagelocator
monitor_mode: true
developer_mode: false
apdex_t: 0.5
log_level:info
ssl:true
capture_params:true
transaction_tracer:
    enabled: true
    record_sql: raw
    stack_trace_threshold: 0.5
    transaction_threshold: apdex_f
    explain_enabled: true
    explain_threshold: 2
error_collector:
    enabled: true
    capture_source: true